/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileIndexRouteImport } from './routes/mobile/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DemoVoiceInputRouteImport } from './routes/demo/voice-input'
import { Route as DemoReceiptCaptureRouteImport } from './routes/demo/receipt-capture'
import { Route as DemoOcrReceiptRouteImport } from './routes/demo/ocr-receipt'
import { Route as DemoDashboardRouteImport } from './routes/demo/dashboard'
import { Route as DashboardTaskThreadsRouteImport } from './routes/dashboard/task-threads'
import { Route as DashboardTaskRulesRouteImport } from './routes/dashboard/task-rules'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSearchRouteImport } from './routes/dashboard/search'
import { Route as DashboardQueryRouteImport } from './routes/dashboard/query'
import { Route as DashboardInboxRouteImport } from './routes/dashboard/inbox'
import { Route as ProfileUserIdIndexRouteImport } from './routes/profile/$userId/index'
import { Route as MobileVouchersIndexRouteImport } from './routes/mobile/vouchers/index'
import { Route as MobileTopupIndexRouteImport } from './routes/mobile/topup/index'
import { Route as MobilePayIndexRouteImport } from './routes/mobile/pay/index'
import { Route as MobileKycIndexRouteImport } from './routes/mobile/kyc/index'
import { Route as MobileFieldTechIndexRouteImport } from './routes/mobile/field-tech/index'
import { Route as MobileExpensesIndexRouteImport } from './routes/mobile/expenses/index'
import { Route as MobileCallIndexRouteImport } from './routes/mobile/call/index'
import { Route as MobileBriefingIndexRouteImport } from './routes/mobile/briefing/index'
import { Route as MobileApprovalsIndexRouteImport } from './routes/mobile/approvals/index'
import { Route as DashboardWalletIndexRouteImport } from './routes/dashboard/wallet/index'
import { Route as DashboardVouchersIndexRouteImport } from './routes/dashboard/vouchers/index'
import { Route as DashboardSalesIndexRouteImport } from './routes/dashboard/sales/index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard/reports/index'
import { Route as DashboardReconciliationIndexRouteImport } from './routes/dashboard/reconciliation/index'
import { Route as DashboardMdIndexRouteImport } from './routes/dashboard/md/index'
import { Route as DashboardKycIndexRouteImport } from './routes/dashboard/kyc/index'
import { Route as DashboardCustomerIssuesIndexRouteImport } from './routes/dashboard/customer-issues/index'
import { Route as DashboardApprovalsIndexRouteImport } from './routes/dashboard/approvals/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as ApiKycIndexRouteImport } from './routes/api/kyc/index'
import { Route as ApiDataExportIndexRouteImport } from './routes/api/data-export/index'
import { Route as MobileVouchersIdRouteImport } from './routes/mobile/vouchers/$id'
import { Route as MobileTopupHistoryRouteImport } from './routes/mobile/topup/history'
import { Route as MobileTopupTransactionIdRouteImport } from './routes/mobile/topup/$transactionId'
import { Route as MobilePostCallCallIdRouteImport } from './routes/mobile/post-call/$callId'
import { Route as MobilePayCodeRouteImport } from './routes/mobile/pay/$code'
import { Route as MobileKycSubmitRouteImport } from './routes/mobile/kyc/submit'
import { Route as MobileFieldTechWorkOrdersRouteImport } from './routes/mobile/field-tech/work-orders'
import { Route as MobileFieldTechRoutePlanRouteImport } from './routes/mobile/field-tech/route-plan'
import { Route as MobileFieldTechInventoryRouteImport } from './routes/mobile/field-tech/inventory'
import { Route as MobileFieldTechHistoryRouteImport } from './routes/mobile/field-tech/history'
import { Route as MobileExpensesNewRouteImport } from './routes/mobile/expenses/new'
import { Route as MobileExpensesIdRouteImport } from './routes/mobile/expenses/$id'
import { Route as MobileCallPhoneOrUserIdRouteImport } from './routes/mobile/call/$phoneOrUserId'
import { Route as DashboardWalletTransactionsRouteImport } from './routes/dashboard/wallet/transactions'
import { Route as DashboardVouchersCreateRouteImport } from './routes/dashboard/vouchers/create'
import { Route as DashboardVouchersIdRouteImport } from './routes/dashboard/vouchers/$id'
import { Route as ApiWorkflowsWebhookRouteImport } from './routes/api/workflows/webhook'
import { Route as ApiWorkflowsProcessRouteImport } from './routes/api/workflows/process'
import { Route as ApiWorkflowsEventRouteImport } from './routes/api/workflows/event'
import { Route as ApiVoucherAlertsMonitorRouteImport } from './routes/api/voucher-alerts/monitor'
import { Route as ApiTeamCapacityMonitorRouteImport } from './routes/api/team-capacity/monitor'
import { Route as ApiTasksRemindersRouteImport } from './routes/api/tasks/reminders'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiRecordingWebhookRouteImport } from './routes/api/recording/webhook'
import { Route as ApiRecordingRetentionRouteImport } from './routes/api/recording/retention'
import { Route as ApiPushProcessQueueRouteImport } from './routes/api/push/process-queue'
import { Route as ApiPushDeepLinkRouteImport } from './routes/api/push/deep-link'
import { Route as ApiPushAndroidInteractionRouteImport } from './routes/api/push/android-interaction'
import { Route as ApiPushAndroidConfigRouteImport } from './routes/api/push/android-config'
import { Route as ApiOverdueTasksMonitorRouteImport } from './routes/api/overdue-tasks/monitor'
import { Route as ApiOnboardingVerifyOtpRouteImport } from './routes/api/onboarding/verify-otp'
import { Route as ApiOnboardingStartRouteImport } from './routes/api/onboarding/start'
import { Route as ApiOnboardingSessionRouteImport } from './routes/api/onboarding/session'
import { Route as ApiOnboardingResendOtpRouteImport } from './routes/api/onboarding/resend-otp'
import { Route as ApiOnboardingLinkAccountRouteImport } from './routes/api/onboarding/link-account'
import { Route as ApiMonitoringStatusRouteImport } from './routes/api/monitoring/status'
import { Route as ApiMonitoringHealthCheckRouteImport } from './routes/api/monitoring/health-check'
import { Route as ApiMonitoringAlertsRouteImport } from './routes/api/monitoring/alerts'
import { Route as ApiKycTiersRouteImport } from './routes/api/kyc/tiers'
import { Route as ApiKycSubmitRouteImport } from './routes/api/kyc/submit'
import { Route as ApiKycDocumentsRouteImport } from './routes/api/kyc/documents'
import { Route as ApiKycAdminRouteImport } from './routes/api/kyc/admin'
import { Route as ApiJobsStatusRouteImport } from './routes/api/jobs/status'
import { Route as ApiJobsProcessRouteImport } from './routes/api/jobs/process'
import { Route as ApiJobsManageRouteImport } from './routes/api/jobs/manage'
import { Route as ApiJobsEnqueueRouteImport } from './routes/api/jobs/enqueue'
import { Route as ApiFeatureFlagsSseRouteImport } from './routes/api/feature-flags/sse'
import { Route as ApiFeatureFlagsHealthRouteImport } from './routes/api/feature-flags/health'
import { Route as ApiExpenseComplianceMonitorRouteImport } from './routes/api/expense-compliance/monitor'
import { Route as ApiCustomerIssuesStatsRouteImport } from './routes/api/customer-issues/stats'
import { Route as ApiCustomerIssuesSlaRouteImport } from './routes/api/customer-issues/sla'
import { Route as ApiCustomerIssuesRisksRouteImport } from './routes/api/customer-issues/risks'
import { Route as ApiCustomerIssuesMonitorRouteImport } from './routes/api/customer-issues/monitor'
import { Route as ApiBriefingScheduleRouteImport } from './routes/api/briefing/schedule'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAnomalyDetectionAnalyzeRouteImport } from './routes/api/anomaly-detection/analyze'
import { Route as ApiAnomalyDetectionAlertsRouteImport } from './routes/api/anomaly-detection/alerts'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/mobile/',
  path: '/mobile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoVoiceInputRoute = DemoVoiceInputRouteImport.update({
  id: '/demo/voice-input',
  path: '/demo/voice-input',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoReceiptCaptureRoute = DemoReceiptCaptureRouteImport.update({
  id: '/demo/receipt-capture',
  path: '/demo/receipt-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOcrReceiptRoute = DemoOcrReceiptRouteImport.update({
  id: '/demo/ocr-receipt',
  path: '/demo/ocr-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/demo/dashboard',
  path: '/demo/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTaskThreadsRoute = DashboardTaskThreadsRouteImport.update({
  id: '/task-threads',
  path: '/task-threads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTaskRulesRoute = DashboardTaskRulesRouteImport.update({
  id: '/task-rules',
  path: '/task-rules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueryRoute = DashboardQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const ProfileUserIdIndexRoute = ProfileUserIdIndexRouteImport.update({
  id: '/profile/$userId/',
  path: '/profile/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileVouchersIndexRoute = MobileVouchersIndexRouteImport.update({
  id: '/mobile/vouchers/',
  path: '/mobile/vouchers/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileTopupIndexRoute = MobileTopupIndexRouteImport.update({
  id: '/mobile/topup/',
  path: '/mobile/topup/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilePayIndexRoute = MobilePayIndexRouteImport.update({
  id: '/mobile/pay/',
  path: '/mobile/pay/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileKycIndexRoute = MobileKycIndexRouteImport.update({
  id: '/mobile/kyc/',
  path: '/mobile/kyc/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileFieldTechIndexRoute = MobileFieldTechIndexRouteImport.update({
  id: '/mobile/field-tech/',
  path: '/mobile/field-tech/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileExpensesIndexRoute = MobileExpensesIndexRouteImport.update({
  id: '/mobile/expenses/',
  path: '/mobile/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileCallIndexRoute = MobileCallIndexRouteImport.update({
  id: '/mobile/call/',
  path: '/mobile/call/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileBriefingIndexRoute = MobileBriefingIndexRouteImport.update({
  id: '/mobile/briefing/',
  path: '/mobile/briefing/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileApprovalsIndexRoute = MobileApprovalsIndexRouteImport.update({
  id: '/mobile/approvals/',
  path: '/mobile/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletIndexRoute = DashboardWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVouchersIndexRoute = DashboardVouchersIndexRouteImport.update({
  id: '/vouchers/',
  path: '/vouchers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalesIndexRoute = DashboardSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReconciliationIndexRoute =
  DashboardReconciliationIndexRouteImport.update({
    id: '/reconciliation/',
    path: '/reconciliation/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMdIndexRoute = DashboardMdIndexRouteImport.update({
  id: '/md/',
  path: '/md/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKycIndexRoute = DashboardKycIndexRouteImport.update({
  id: '/kyc/',
  path: '/kyc/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomerIssuesIndexRoute =
  DashboardCustomerIssuesIndexRouteImport.update({
    id: '/customer-issues/',
    path: '/customer-issues/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardApprovalsIndexRoute = DashboardApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiKycIndexRoute = ApiKycIndexRouteImport.update({
  id: '/api/kyc/',
  path: '/api/kyc/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataExportIndexRoute = ApiDataExportIndexRouteImport.update({
  id: '/api/data-export/',
  path: '/api/data-export/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileVouchersIdRoute = MobileVouchersIdRouteImport.update({
  id: '/mobile/vouchers/$id',
  path: '/mobile/vouchers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileTopupHistoryRoute = MobileTopupHistoryRouteImport.update({
  id: '/mobile/topup/history',
  path: '/mobile/topup/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileTopupTransactionIdRoute =
  MobileTopupTransactionIdRouteImport.update({
    id: '/mobile/topup/$transactionId',
    path: '/mobile/topup/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MobilePostCallCallIdRoute = MobilePostCallCallIdRouteImport.update({
  id: '/mobile/post-call/$callId',
  path: '/mobile/post-call/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilePayCodeRoute = MobilePayCodeRouteImport.update({
  id: '/mobile/pay/$code',
  path: '/mobile/pay/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileKycSubmitRoute = MobileKycSubmitRouteImport.update({
  id: '/mobile/kyc/submit',
  path: '/mobile/kyc/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileFieldTechWorkOrdersRoute =
  MobileFieldTechWorkOrdersRouteImport.update({
    id: '/mobile/field-tech/work-orders',
    path: '/mobile/field-tech/work-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const MobileFieldTechRoutePlanRoute =
  MobileFieldTechRoutePlanRouteImport.update({
    id: '/mobile/field-tech/route-plan',
    path: '/mobile/field-tech/route-plan',
    getParentRoute: () => rootRouteImport,
  } as any)
const MobileFieldTechInventoryRoute =
  MobileFieldTechInventoryRouteImport.update({
    id: '/mobile/field-tech/inventory',
    path: '/mobile/field-tech/inventory',
    getParentRoute: () => rootRouteImport,
  } as any)
const MobileFieldTechHistoryRoute = MobileFieldTechHistoryRouteImport.update({
  id: '/mobile/field-tech/history',
  path: '/mobile/field-tech/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileExpensesNewRoute = MobileExpensesNewRouteImport.update({
  id: '/mobile/expenses/new',
  path: '/mobile/expenses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileExpensesIdRoute = MobileExpensesIdRouteImport.update({
  id: '/mobile/expenses/$id',
  path: '/mobile/expenses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileCallPhoneOrUserIdRoute = MobileCallPhoneOrUserIdRouteImport.update({
  id: '/mobile/call/$phoneOrUserId',
  path: '/mobile/call/$phoneOrUserId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletTransactionsRoute =
  DashboardWalletTransactionsRouteImport.update({
    id: '/wallet/transactions',
    path: '/wallet/transactions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardVouchersCreateRoute = DashboardVouchersCreateRouteImport.update({
  id: '/vouchers/create',
  path: '/vouchers/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVouchersIdRoute = DashboardVouchersIdRouteImport.update({
  id: '/vouchers/$id',
  path: '/vouchers/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiWorkflowsWebhookRoute = ApiWorkflowsWebhookRouteImport.update({
  id: '/api/workflows/webhook',
  path: '/api/workflows/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsProcessRoute = ApiWorkflowsProcessRouteImport.update({
  id: '/api/workflows/process',
  path: '/api/workflows/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsEventRoute = ApiWorkflowsEventRouteImport.update({
  id: '/api/workflows/event',
  path: '/api/workflows/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoucherAlertsMonitorRoute = ApiVoucherAlertsMonitorRouteImport.update({
  id: '/api/voucher-alerts/monitor',
  path: '/api/voucher-alerts/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamCapacityMonitorRoute = ApiTeamCapacityMonitorRouteImport.update({
  id: '/api/team-capacity/monitor',
  path: '/api/team-capacity/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRemindersRoute = ApiTasksRemindersRouteImport.update({
  id: '/api/tasks/reminders',
  path: '/api/tasks/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordingWebhookRoute = ApiRecordingWebhookRouteImport.update({
  id: '/api/recording/webhook',
  path: '/api/recording/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordingRetentionRoute = ApiRecordingRetentionRouteImport.update({
  id: '/api/recording/retention',
  path: '/api/recording/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushProcessQueueRoute = ApiPushProcessQueueRouteImport.update({
  id: '/api/push/process-queue',
  path: '/api/push/process-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushDeepLinkRoute = ApiPushDeepLinkRouteImport.update({
  id: '/api/push/deep-link',
  path: '/api/push/deep-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushAndroidInteractionRoute =
  ApiPushAndroidInteractionRouteImport.update({
    id: '/api/push/android-interaction',
    path: '/api/push/android-interaction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPushAndroidConfigRoute = ApiPushAndroidConfigRouteImport.update({
  id: '/api/push/android-config',
  path: '/api/push/android-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverdueTasksMonitorRoute = ApiOverdueTasksMonitorRouteImport.update({
  id: '/api/overdue-tasks/monitor',
  path: '/api/overdue-tasks/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingVerifyOtpRoute = ApiOnboardingVerifyOtpRouteImport.update({
  id: '/api/onboarding/verify-otp',
  path: '/api/onboarding/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingStartRoute = ApiOnboardingStartRouteImport.update({
  id: '/api/onboarding/start',
  path: '/api/onboarding/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingSessionRoute = ApiOnboardingSessionRouteImport.update({
  id: '/api/onboarding/session',
  path: '/api/onboarding/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingResendOtpRoute = ApiOnboardingResendOtpRouteImport.update({
  id: '/api/onboarding/resend-otp',
  path: '/api/onboarding/resend-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingLinkAccountRoute =
  ApiOnboardingLinkAccountRouteImport.update({
    id: '/api/onboarding/link-account',
    path: '/api/onboarding/link-account',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMonitoringStatusRoute = ApiMonitoringStatusRouteImport.update({
  id: '/api/monitoring/status',
  path: '/api/monitoring/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitoringHealthCheckRoute =
  ApiMonitoringHealthCheckRouteImport.update({
    id: '/api/monitoring/health-check',
    path: '/api/monitoring/health-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMonitoringAlertsRoute = ApiMonitoringAlertsRouteImport.update({
  id: '/api/monitoring/alerts',
  path: '/api/monitoring/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKycTiersRoute = ApiKycTiersRouteImport.update({
  id: '/api/kyc/tiers',
  path: '/api/kyc/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKycSubmitRoute = ApiKycSubmitRouteImport.update({
  id: '/api/kyc/submit',
  path: '/api/kyc/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKycDocumentsRoute = ApiKycDocumentsRouteImport.update({
  id: '/api/kyc/documents',
  path: '/api/kyc/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKycAdminRoute = ApiKycAdminRouteImport.update({
  id: '/api/kyc/admin',
  path: '/api/kyc/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsStatusRoute = ApiJobsStatusRouteImport.update({
  id: '/api/jobs/status',
  path: '/api/jobs/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsProcessRoute = ApiJobsProcessRouteImport.update({
  id: '/api/jobs/process',
  path: '/api/jobs/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsManageRoute = ApiJobsManageRouteImport.update({
  id: '/api/jobs/manage',
  path: '/api/jobs/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsEnqueueRoute = ApiJobsEnqueueRouteImport.update({
  id: '/api/jobs/enqueue',
  path: '/api/jobs/enqueue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeatureFlagsSseRoute = ApiFeatureFlagsSseRouteImport.update({
  id: '/api/feature-flags/sse',
  path: '/api/feature-flags/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeatureFlagsHealthRoute = ApiFeatureFlagsHealthRouteImport.update({
  id: '/api/feature-flags/health',
  path: '/api/feature-flags/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpenseComplianceMonitorRoute =
  ApiExpenseComplianceMonitorRouteImport.update({
    id: '/api/expense-compliance/monitor',
    path: '/api/expense-compliance/monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCustomerIssuesStatsRoute = ApiCustomerIssuesStatsRouteImport.update({
  id: '/api/customer-issues/stats',
  path: '/api/customer-issues/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerIssuesSlaRoute = ApiCustomerIssuesSlaRouteImport.update({
  id: '/api/customer-issues/sla',
  path: '/api/customer-issues/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerIssuesRisksRoute = ApiCustomerIssuesRisksRouteImport.update({
  id: '/api/customer-issues/risks',
  path: '/api/customer-issues/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerIssuesMonitorRoute =
  ApiCustomerIssuesMonitorRouteImport.update({
    id: '/api/customer-issues/monitor',
    path: '/api/customer-issues/monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBriefingScheduleRoute = ApiBriefingScheduleRouteImport.update({
  id: '/api/briefing/schedule',
  path: '/api/briefing/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnomalyDetectionAnalyzeRoute =
  ApiAnomalyDetectionAnalyzeRouteImport.update({
    id: '/api/anomaly-detection/analyze',
    path: '/api/anomaly-detection/analyze',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnomalyDetectionAlertsRoute =
  ApiAnomalyDetectionAlertsRouteImport.update({
    id: '/api/anomaly-detection/alerts',
    path: '/api/anomaly-detection/alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/query': typeof DashboardQueryRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/task-rules': typeof DashboardTaskRulesRoute
  '/dashboard/task-threads': typeof DashboardTaskThreadsRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/ocr-receipt': typeof DemoOcrReceiptRoute
  '/demo/receipt-capture': typeof DemoReceiptCaptureRoute
  '/demo/voice-input': typeof DemoVoiceInputRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo': typeof DemoIndexRoute
  '/mobile': typeof MobileIndexRoute
  '/api/anomaly-detection/alerts': typeof ApiAnomalyDetectionAlertsRoute
  '/api/anomaly-detection/analyze': typeof ApiAnomalyDetectionAnalyzeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/briefing/schedule': typeof ApiBriefingScheduleRoute
  '/api/customer-issues/monitor': typeof ApiCustomerIssuesMonitorRoute
  '/api/customer-issues/risks': typeof ApiCustomerIssuesRisksRoute
  '/api/customer-issues/sla': typeof ApiCustomerIssuesSlaRoute
  '/api/customer-issues/stats': typeof ApiCustomerIssuesStatsRoute
  '/api/expense-compliance/monitor': typeof ApiExpenseComplianceMonitorRoute
  '/api/feature-flags/health': typeof ApiFeatureFlagsHealthRoute
  '/api/feature-flags/sse': typeof ApiFeatureFlagsSseRoute
  '/api/jobs/enqueue': typeof ApiJobsEnqueueRoute
  '/api/jobs/manage': typeof ApiJobsManageRoute
  '/api/jobs/process': typeof ApiJobsProcessRoute
  '/api/jobs/status': typeof ApiJobsStatusRoute
  '/api/kyc/admin': typeof ApiKycAdminRoute
  '/api/kyc/documents': typeof ApiKycDocumentsRoute
  '/api/kyc/submit': typeof ApiKycSubmitRoute
  '/api/kyc/tiers': typeof ApiKycTiersRoute
  '/api/monitoring/alerts': typeof ApiMonitoringAlertsRoute
  '/api/monitoring/health-check': typeof ApiMonitoringHealthCheckRoute
  '/api/monitoring/status': typeof ApiMonitoringStatusRoute
  '/api/onboarding/link-account': typeof ApiOnboardingLinkAccountRoute
  '/api/onboarding/resend-otp': typeof ApiOnboardingResendOtpRoute
  '/api/onboarding/session': typeof ApiOnboardingSessionRoute
  '/api/onboarding/start': typeof ApiOnboardingStartRoute
  '/api/onboarding/verify-otp': typeof ApiOnboardingVerifyOtpRoute
  '/api/overdue-tasks/monitor': typeof ApiOverdueTasksMonitorRoute
  '/api/push/android-config': typeof ApiPushAndroidConfigRoute
  '/api/push/android-interaction': typeof ApiPushAndroidInteractionRoute
  '/api/push/deep-link': typeof ApiPushDeepLinkRoute
  '/api/push/process-queue': typeof ApiPushProcessQueueRoute
  '/api/recording/retention': typeof ApiRecordingRetentionRoute
  '/api/recording/webhook': typeof ApiRecordingWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/tasks/reminders': typeof ApiTasksRemindersRoute
  '/api/team-capacity/monitor': typeof ApiTeamCapacityMonitorRoute
  '/api/voucher-alerts/monitor': typeof ApiVoucherAlertsMonitorRoute
  '/api/workflows/event': typeof ApiWorkflowsEventRoute
  '/api/workflows/process': typeof ApiWorkflowsProcessRoute
  '/api/workflows/webhook': typeof ApiWorkflowsWebhookRoute
  '/dashboard/vouchers/$id': typeof DashboardVouchersIdRoute
  '/dashboard/vouchers/create': typeof DashboardVouchersCreateRoute
  '/dashboard/wallet/transactions': typeof DashboardWalletTransactionsRoute
  '/mobile/call/$phoneOrUserId': typeof MobileCallPhoneOrUserIdRoute
  '/mobile/expenses/$id': typeof MobileExpensesIdRoute
  '/mobile/expenses/new': typeof MobileExpensesNewRoute
  '/mobile/field-tech/history': typeof MobileFieldTechHistoryRoute
  '/mobile/field-tech/inventory': typeof MobileFieldTechInventoryRoute
  '/mobile/field-tech/route-plan': typeof MobileFieldTechRoutePlanRoute
  '/mobile/field-tech/work-orders': typeof MobileFieldTechWorkOrdersRoute
  '/mobile/kyc/submit': typeof MobileKycSubmitRoute
  '/mobile/pay/$code': typeof MobilePayCodeRoute
  '/mobile/post-call/$callId': typeof MobilePostCallCallIdRoute
  '/mobile/topup/$transactionId': typeof MobileTopupTransactionIdRoute
  '/mobile/topup/history': typeof MobileTopupHistoryRoute
  '/mobile/vouchers/$id': typeof MobileVouchersIdRoute
  '/api/data-export': typeof ApiDataExportIndexRoute
  '/api/kyc': typeof ApiKycIndexRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/approvals': typeof DashboardApprovalsIndexRoute
  '/dashboard/customer-issues': typeof DashboardCustomerIssuesIndexRoute
  '/dashboard/kyc': typeof DashboardKycIndexRoute
  '/dashboard/md': typeof DashboardMdIndexRoute
  '/dashboard/reconciliation': typeof DashboardReconciliationIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/sales': typeof DashboardSalesIndexRoute
  '/dashboard/vouchers': typeof DashboardVouchersIndexRoute
  '/dashboard/wallet': typeof DashboardWalletIndexRoute
  '/mobile/approvals': typeof MobileApprovalsIndexRoute
  '/mobile/briefing': typeof MobileBriefingIndexRoute
  '/mobile/call': typeof MobileCallIndexRoute
  '/mobile/expenses': typeof MobileExpensesIndexRoute
  '/mobile/field-tech': typeof MobileFieldTechIndexRoute
  '/mobile/kyc': typeof MobileKycIndexRoute
  '/mobile/pay': typeof MobilePayIndexRoute
  '/mobile/topup': typeof MobileTopupIndexRoute
  '/mobile/vouchers': typeof MobileVouchersIndexRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/query': typeof DashboardQueryRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/task-rules': typeof DashboardTaskRulesRoute
  '/dashboard/task-threads': typeof DashboardTaskThreadsRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/ocr-receipt': typeof DemoOcrReceiptRoute
  '/demo/receipt-capture': typeof DemoReceiptCaptureRoute
  '/demo/voice-input': typeof DemoVoiceInputRoute
  '/dashboard': typeof DashboardIndexRoute
  '/demo': typeof DemoIndexRoute
  '/mobile': typeof MobileIndexRoute
  '/api/anomaly-detection/alerts': typeof ApiAnomalyDetectionAlertsRoute
  '/api/anomaly-detection/analyze': typeof ApiAnomalyDetectionAnalyzeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/briefing/schedule': typeof ApiBriefingScheduleRoute
  '/api/customer-issues/monitor': typeof ApiCustomerIssuesMonitorRoute
  '/api/customer-issues/risks': typeof ApiCustomerIssuesRisksRoute
  '/api/customer-issues/sla': typeof ApiCustomerIssuesSlaRoute
  '/api/customer-issues/stats': typeof ApiCustomerIssuesStatsRoute
  '/api/expense-compliance/monitor': typeof ApiExpenseComplianceMonitorRoute
  '/api/feature-flags/health': typeof ApiFeatureFlagsHealthRoute
  '/api/feature-flags/sse': typeof ApiFeatureFlagsSseRoute
  '/api/jobs/enqueue': typeof ApiJobsEnqueueRoute
  '/api/jobs/manage': typeof ApiJobsManageRoute
  '/api/jobs/process': typeof ApiJobsProcessRoute
  '/api/jobs/status': typeof ApiJobsStatusRoute
  '/api/kyc/admin': typeof ApiKycAdminRoute
  '/api/kyc/documents': typeof ApiKycDocumentsRoute
  '/api/kyc/submit': typeof ApiKycSubmitRoute
  '/api/kyc/tiers': typeof ApiKycTiersRoute
  '/api/monitoring/alerts': typeof ApiMonitoringAlertsRoute
  '/api/monitoring/health-check': typeof ApiMonitoringHealthCheckRoute
  '/api/monitoring/status': typeof ApiMonitoringStatusRoute
  '/api/onboarding/link-account': typeof ApiOnboardingLinkAccountRoute
  '/api/onboarding/resend-otp': typeof ApiOnboardingResendOtpRoute
  '/api/onboarding/session': typeof ApiOnboardingSessionRoute
  '/api/onboarding/start': typeof ApiOnboardingStartRoute
  '/api/onboarding/verify-otp': typeof ApiOnboardingVerifyOtpRoute
  '/api/overdue-tasks/monitor': typeof ApiOverdueTasksMonitorRoute
  '/api/push/android-config': typeof ApiPushAndroidConfigRoute
  '/api/push/android-interaction': typeof ApiPushAndroidInteractionRoute
  '/api/push/deep-link': typeof ApiPushDeepLinkRoute
  '/api/push/process-queue': typeof ApiPushProcessQueueRoute
  '/api/recording/retention': typeof ApiRecordingRetentionRoute
  '/api/recording/webhook': typeof ApiRecordingWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/tasks/reminders': typeof ApiTasksRemindersRoute
  '/api/team-capacity/monitor': typeof ApiTeamCapacityMonitorRoute
  '/api/voucher-alerts/monitor': typeof ApiVoucherAlertsMonitorRoute
  '/api/workflows/event': typeof ApiWorkflowsEventRoute
  '/api/workflows/process': typeof ApiWorkflowsProcessRoute
  '/api/workflows/webhook': typeof ApiWorkflowsWebhookRoute
  '/dashboard/vouchers/$id': typeof DashboardVouchersIdRoute
  '/dashboard/vouchers/create': typeof DashboardVouchersCreateRoute
  '/dashboard/wallet/transactions': typeof DashboardWalletTransactionsRoute
  '/mobile/call/$phoneOrUserId': typeof MobileCallPhoneOrUserIdRoute
  '/mobile/expenses/$id': typeof MobileExpensesIdRoute
  '/mobile/expenses/new': typeof MobileExpensesNewRoute
  '/mobile/field-tech/history': typeof MobileFieldTechHistoryRoute
  '/mobile/field-tech/inventory': typeof MobileFieldTechInventoryRoute
  '/mobile/field-tech/route-plan': typeof MobileFieldTechRoutePlanRoute
  '/mobile/field-tech/work-orders': typeof MobileFieldTechWorkOrdersRoute
  '/mobile/kyc/submit': typeof MobileKycSubmitRoute
  '/mobile/pay/$code': typeof MobilePayCodeRoute
  '/mobile/post-call/$callId': typeof MobilePostCallCallIdRoute
  '/mobile/topup/$transactionId': typeof MobileTopupTransactionIdRoute
  '/mobile/topup/history': typeof MobileTopupHistoryRoute
  '/mobile/vouchers/$id': typeof MobileVouchersIdRoute
  '/api/data-export': typeof ApiDataExportIndexRoute
  '/api/kyc': typeof ApiKycIndexRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/approvals': typeof DashboardApprovalsIndexRoute
  '/dashboard/customer-issues': typeof DashboardCustomerIssuesIndexRoute
  '/dashboard/kyc': typeof DashboardKycIndexRoute
  '/dashboard/md': typeof DashboardMdIndexRoute
  '/dashboard/reconciliation': typeof DashboardReconciliationIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/sales': typeof DashboardSalesIndexRoute
  '/dashboard/vouchers': typeof DashboardVouchersIndexRoute
  '/dashboard/wallet': typeof DashboardWalletIndexRoute
  '/mobile/approvals': typeof MobileApprovalsIndexRoute
  '/mobile/briefing': typeof MobileBriefingIndexRoute
  '/mobile/call': typeof MobileCallIndexRoute
  '/mobile/expenses': typeof MobileExpensesIndexRoute
  '/mobile/field-tech': typeof MobileFieldTechIndexRoute
  '/mobile/kyc': typeof MobileKycIndexRoute
  '/mobile/pay': typeof MobilePayIndexRoute
  '/mobile/topup': typeof MobileTopupIndexRoute
  '/mobile/vouchers': typeof MobileVouchersIndexRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/query': typeof DashboardQueryRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/task-rules': typeof DashboardTaskRulesRoute
  '/dashboard/task-threads': typeof DashboardTaskThreadsRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/ocr-receipt': typeof DemoOcrReceiptRoute
  '/demo/receipt-capture': typeof DemoReceiptCaptureRoute
  '/demo/voice-input': typeof DemoVoiceInputRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/api/anomaly-detection/alerts': typeof ApiAnomalyDetectionAlertsRoute
  '/api/anomaly-detection/analyze': typeof ApiAnomalyDetectionAnalyzeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/briefing/schedule': typeof ApiBriefingScheduleRoute
  '/api/customer-issues/monitor': typeof ApiCustomerIssuesMonitorRoute
  '/api/customer-issues/risks': typeof ApiCustomerIssuesRisksRoute
  '/api/customer-issues/sla': typeof ApiCustomerIssuesSlaRoute
  '/api/customer-issues/stats': typeof ApiCustomerIssuesStatsRoute
  '/api/expense-compliance/monitor': typeof ApiExpenseComplianceMonitorRoute
  '/api/feature-flags/health': typeof ApiFeatureFlagsHealthRoute
  '/api/feature-flags/sse': typeof ApiFeatureFlagsSseRoute
  '/api/jobs/enqueue': typeof ApiJobsEnqueueRoute
  '/api/jobs/manage': typeof ApiJobsManageRoute
  '/api/jobs/process': typeof ApiJobsProcessRoute
  '/api/jobs/status': typeof ApiJobsStatusRoute
  '/api/kyc/admin': typeof ApiKycAdminRoute
  '/api/kyc/documents': typeof ApiKycDocumentsRoute
  '/api/kyc/submit': typeof ApiKycSubmitRoute
  '/api/kyc/tiers': typeof ApiKycTiersRoute
  '/api/monitoring/alerts': typeof ApiMonitoringAlertsRoute
  '/api/monitoring/health-check': typeof ApiMonitoringHealthCheckRoute
  '/api/monitoring/status': typeof ApiMonitoringStatusRoute
  '/api/onboarding/link-account': typeof ApiOnboardingLinkAccountRoute
  '/api/onboarding/resend-otp': typeof ApiOnboardingResendOtpRoute
  '/api/onboarding/session': typeof ApiOnboardingSessionRoute
  '/api/onboarding/start': typeof ApiOnboardingStartRoute
  '/api/onboarding/verify-otp': typeof ApiOnboardingVerifyOtpRoute
  '/api/overdue-tasks/monitor': typeof ApiOverdueTasksMonitorRoute
  '/api/push/android-config': typeof ApiPushAndroidConfigRoute
  '/api/push/android-interaction': typeof ApiPushAndroidInteractionRoute
  '/api/push/deep-link': typeof ApiPushDeepLinkRoute
  '/api/push/process-queue': typeof ApiPushProcessQueueRoute
  '/api/recording/retention': typeof ApiRecordingRetentionRoute
  '/api/recording/webhook': typeof ApiRecordingWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/tasks/reminders': typeof ApiTasksRemindersRoute
  '/api/team-capacity/monitor': typeof ApiTeamCapacityMonitorRoute
  '/api/voucher-alerts/monitor': typeof ApiVoucherAlertsMonitorRoute
  '/api/workflows/event': typeof ApiWorkflowsEventRoute
  '/api/workflows/process': typeof ApiWorkflowsProcessRoute
  '/api/workflows/webhook': typeof ApiWorkflowsWebhookRoute
  '/dashboard/vouchers/$id': typeof DashboardVouchersIdRoute
  '/dashboard/vouchers/create': typeof DashboardVouchersCreateRoute
  '/dashboard/wallet/transactions': typeof DashboardWalletTransactionsRoute
  '/mobile/call/$phoneOrUserId': typeof MobileCallPhoneOrUserIdRoute
  '/mobile/expenses/$id': typeof MobileExpensesIdRoute
  '/mobile/expenses/new': typeof MobileExpensesNewRoute
  '/mobile/field-tech/history': typeof MobileFieldTechHistoryRoute
  '/mobile/field-tech/inventory': typeof MobileFieldTechInventoryRoute
  '/mobile/field-tech/route-plan': typeof MobileFieldTechRoutePlanRoute
  '/mobile/field-tech/work-orders': typeof MobileFieldTechWorkOrdersRoute
  '/mobile/kyc/submit': typeof MobileKycSubmitRoute
  '/mobile/pay/$code': typeof MobilePayCodeRoute
  '/mobile/post-call/$callId': typeof MobilePostCallCallIdRoute
  '/mobile/topup/$transactionId': typeof MobileTopupTransactionIdRoute
  '/mobile/topup/history': typeof MobileTopupHistoryRoute
  '/mobile/vouchers/$id': typeof MobileVouchersIdRoute
  '/api/data-export/': typeof ApiDataExportIndexRoute
  '/api/kyc/': typeof ApiKycIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/approvals/': typeof DashboardApprovalsIndexRoute
  '/dashboard/customer-issues/': typeof DashboardCustomerIssuesIndexRoute
  '/dashboard/kyc/': typeof DashboardKycIndexRoute
  '/dashboard/md/': typeof DashboardMdIndexRoute
  '/dashboard/reconciliation/': typeof DashboardReconciliationIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/sales/': typeof DashboardSalesIndexRoute
  '/dashboard/vouchers/': typeof DashboardVouchersIndexRoute
  '/dashboard/wallet/': typeof DashboardWalletIndexRoute
  '/mobile/approvals/': typeof MobileApprovalsIndexRoute
  '/mobile/briefing/': typeof MobileBriefingIndexRoute
  '/mobile/call/': typeof MobileCallIndexRoute
  '/mobile/expenses/': typeof MobileExpensesIndexRoute
  '/mobile/field-tech/': typeof MobileFieldTechIndexRoute
  '/mobile/kyc/': typeof MobileKycIndexRoute
  '/mobile/pay/': typeof MobilePayIndexRoute
  '/mobile/topup/': typeof MobileTopupIndexRoute
  '/mobile/vouchers/': typeof MobileVouchersIndexRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/inbox'
    | '/dashboard/query'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/task-rules'
    | '/dashboard/task-threads'
    | '/demo/dashboard'
    | '/demo/ocr-receipt'
    | '/demo/receipt-capture'
    | '/demo/voice-input'
    | '/dashboard/'
    | '/demo'
    | '/mobile'
    | '/api/anomaly-detection/alerts'
    | '/api/anomaly-detection/analyze'
    | '/api/auth/$'
    | '/api/briefing/schedule'
    | '/api/customer-issues/monitor'
    | '/api/customer-issues/risks'
    | '/api/customer-issues/sla'
    | '/api/customer-issues/stats'
    | '/api/expense-compliance/monitor'
    | '/api/feature-flags/health'
    | '/api/feature-flags/sse'
    | '/api/jobs/enqueue'
    | '/api/jobs/manage'
    | '/api/jobs/process'
    | '/api/jobs/status'
    | '/api/kyc/admin'
    | '/api/kyc/documents'
    | '/api/kyc/submit'
    | '/api/kyc/tiers'
    | '/api/monitoring/alerts'
    | '/api/monitoring/health-check'
    | '/api/monitoring/status'
    | '/api/onboarding/link-account'
    | '/api/onboarding/resend-otp'
    | '/api/onboarding/session'
    | '/api/onboarding/start'
    | '/api/onboarding/verify-otp'
    | '/api/overdue-tasks/monitor'
    | '/api/push/android-config'
    | '/api/push/android-interaction'
    | '/api/push/deep-link'
    | '/api/push/process-queue'
    | '/api/recording/retention'
    | '/api/recording/webhook'
    | '/api/stripe/webhook'
    | '/api/tasks/reminders'
    | '/api/team-capacity/monitor'
    | '/api/voucher-alerts/monitor'
    | '/api/workflows/event'
    | '/api/workflows/process'
    | '/api/workflows/webhook'
    | '/dashboard/vouchers/$id'
    | '/dashboard/vouchers/create'
    | '/dashboard/wallet/transactions'
    | '/mobile/call/$phoneOrUserId'
    | '/mobile/expenses/$id'
    | '/mobile/expenses/new'
    | '/mobile/field-tech/history'
    | '/mobile/field-tech/inventory'
    | '/mobile/field-tech/route-plan'
    | '/mobile/field-tech/work-orders'
    | '/mobile/kyc/submit'
    | '/mobile/pay/$code'
    | '/mobile/post-call/$callId'
    | '/mobile/topup/$transactionId'
    | '/mobile/topup/history'
    | '/mobile/vouchers/$id'
    | '/api/data-export'
    | '/api/kyc'
    | '/dashboard/admin'
    | '/dashboard/approvals'
    | '/dashboard/customer-issues'
    | '/dashboard/kyc'
    | '/dashboard/md'
    | '/dashboard/reconciliation'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard/vouchers'
    | '/dashboard/wallet'
    | '/mobile/approvals'
    | '/mobile/briefing'
    | '/mobile/call'
    | '/mobile/expenses'
    | '/mobile/field-tech'
    | '/mobile/kyc'
    | '/mobile/pay'
    | '/mobile/topup'
    | '/mobile/vouchers'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/inbox'
    | '/dashboard/query'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/task-rules'
    | '/dashboard/task-threads'
    | '/demo/dashboard'
    | '/demo/ocr-receipt'
    | '/demo/receipt-capture'
    | '/demo/voice-input'
    | '/dashboard'
    | '/demo'
    | '/mobile'
    | '/api/anomaly-detection/alerts'
    | '/api/anomaly-detection/analyze'
    | '/api/auth/$'
    | '/api/briefing/schedule'
    | '/api/customer-issues/monitor'
    | '/api/customer-issues/risks'
    | '/api/customer-issues/sla'
    | '/api/customer-issues/stats'
    | '/api/expense-compliance/monitor'
    | '/api/feature-flags/health'
    | '/api/feature-flags/sse'
    | '/api/jobs/enqueue'
    | '/api/jobs/manage'
    | '/api/jobs/process'
    | '/api/jobs/status'
    | '/api/kyc/admin'
    | '/api/kyc/documents'
    | '/api/kyc/submit'
    | '/api/kyc/tiers'
    | '/api/monitoring/alerts'
    | '/api/monitoring/health-check'
    | '/api/monitoring/status'
    | '/api/onboarding/link-account'
    | '/api/onboarding/resend-otp'
    | '/api/onboarding/session'
    | '/api/onboarding/start'
    | '/api/onboarding/verify-otp'
    | '/api/overdue-tasks/monitor'
    | '/api/push/android-config'
    | '/api/push/android-interaction'
    | '/api/push/deep-link'
    | '/api/push/process-queue'
    | '/api/recording/retention'
    | '/api/recording/webhook'
    | '/api/stripe/webhook'
    | '/api/tasks/reminders'
    | '/api/team-capacity/monitor'
    | '/api/voucher-alerts/monitor'
    | '/api/workflows/event'
    | '/api/workflows/process'
    | '/api/workflows/webhook'
    | '/dashboard/vouchers/$id'
    | '/dashboard/vouchers/create'
    | '/dashboard/wallet/transactions'
    | '/mobile/call/$phoneOrUserId'
    | '/mobile/expenses/$id'
    | '/mobile/expenses/new'
    | '/mobile/field-tech/history'
    | '/mobile/field-tech/inventory'
    | '/mobile/field-tech/route-plan'
    | '/mobile/field-tech/work-orders'
    | '/mobile/kyc/submit'
    | '/mobile/pay/$code'
    | '/mobile/post-call/$callId'
    | '/mobile/topup/$transactionId'
    | '/mobile/topup/history'
    | '/mobile/vouchers/$id'
    | '/api/data-export'
    | '/api/kyc'
    | '/dashboard/admin'
    | '/dashboard/approvals'
    | '/dashboard/customer-issues'
    | '/dashboard/kyc'
    | '/dashboard/md'
    | '/dashboard/reconciliation'
    | '/dashboard/reports'
    | '/dashboard/sales'
    | '/dashboard/vouchers'
    | '/dashboard/wallet'
    | '/mobile/approvals'
    | '/mobile/briefing'
    | '/mobile/call'
    | '/mobile/expenses'
    | '/mobile/field-tech'
    | '/mobile/kyc'
    | '/mobile/pay'
    | '/mobile/topup'
    | '/mobile/vouchers'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/inbox'
    | '/dashboard/query'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/task-rules'
    | '/dashboard/task-threads'
    | '/demo/dashboard'
    | '/demo/ocr-receipt'
    | '/demo/receipt-capture'
    | '/demo/voice-input'
    | '/dashboard/'
    | '/demo/'
    | '/mobile/'
    | '/api/anomaly-detection/alerts'
    | '/api/anomaly-detection/analyze'
    | '/api/auth/$'
    | '/api/briefing/schedule'
    | '/api/customer-issues/monitor'
    | '/api/customer-issues/risks'
    | '/api/customer-issues/sla'
    | '/api/customer-issues/stats'
    | '/api/expense-compliance/monitor'
    | '/api/feature-flags/health'
    | '/api/feature-flags/sse'
    | '/api/jobs/enqueue'
    | '/api/jobs/manage'
    | '/api/jobs/process'
    | '/api/jobs/status'
    | '/api/kyc/admin'
    | '/api/kyc/documents'
    | '/api/kyc/submit'
    | '/api/kyc/tiers'
    | '/api/monitoring/alerts'
    | '/api/monitoring/health-check'
    | '/api/monitoring/status'
    | '/api/onboarding/link-account'
    | '/api/onboarding/resend-otp'
    | '/api/onboarding/session'
    | '/api/onboarding/start'
    | '/api/onboarding/verify-otp'
    | '/api/overdue-tasks/monitor'
    | '/api/push/android-config'
    | '/api/push/android-interaction'
    | '/api/push/deep-link'
    | '/api/push/process-queue'
    | '/api/recording/retention'
    | '/api/recording/webhook'
    | '/api/stripe/webhook'
    | '/api/tasks/reminders'
    | '/api/team-capacity/monitor'
    | '/api/voucher-alerts/monitor'
    | '/api/workflows/event'
    | '/api/workflows/process'
    | '/api/workflows/webhook'
    | '/dashboard/vouchers/$id'
    | '/dashboard/vouchers/create'
    | '/dashboard/wallet/transactions'
    | '/mobile/call/$phoneOrUserId'
    | '/mobile/expenses/$id'
    | '/mobile/expenses/new'
    | '/mobile/field-tech/history'
    | '/mobile/field-tech/inventory'
    | '/mobile/field-tech/route-plan'
    | '/mobile/field-tech/work-orders'
    | '/mobile/kyc/submit'
    | '/mobile/pay/$code'
    | '/mobile/post-call/$callId'
    | '/mobile/topup/$transactionId'
    | '/mobile/topup/history'
    | '/mobile/vouchers/$id'
    | '/api/data-export/'
    | '/api/kyc/'
    | '/dashboard/admin/'
    | '/dashboard/approvals/'
    | '/dashboard/customer-issues/'
    | '/dashboard/kyc/'
    | '/dashboard/md/'
    | '/dashboard/reconciliation/'
    | '/dashboard/reports/'
    | '/dashboard/sales/'
    | '/dashboard/vouchers/'
    | '/dashboard/wallet/'
    | '/mobile/approvals/'
    | '/mobile/briefing/'
    | '/mobile/call/'
    | '/mobile/expenses/'
    | '/mobile/field-tech/'
    | '/mobile/kyc/'
    | '/mobile/pay/'
    | '/mobile/topup/'
    | '/mobile/vouchers/'
    | '/profile/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoOcrReceiptRoute: typeof DemoOcrReceiptRoute
  DemoReceiptCaptureRoute: typeof DemoReceiptCaptureRoute
  DemoVoiceInputRoute: typeof DemoVoiceInputRoute
  DemoIndexRoute: typeof DemoIndexRoute
  MobileIndexRoute: typeof MobileIndexRoute
  ApiAnomalyDetectionAlertsRoute: typeof ApiAnomalyDetectionAlertsRoute
  ApiAnomalyDetectionAnalyzeRoute: typeof ApiAnomalyDetectionAnalyzeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBriefingScheduleRoute: typeof ApiBriefingScheduleRoute
  ApiCustomerIssuesMonitorRoute: typeof ApiCustomerIssuesMonitorRoute
  ApiCustomerIssuesRisksRoute: typeof ApiCustomerIssuesRisksRoute
  ApiCustomerIssuesSlaRoute: typeof ApiCustomerIssuesSlaRoute
  ApiCustomerIssuesStatsRoute: typeof ApiCustomerIssuesStatsRoute
  ApiExpenseComplianceMonitorRoute: typeof ApiExpenseComplianceMonitorRoute
  ApiFeatureFlagsHealthRoute: typeof ApiFeatureFlagsHealthRoute
  ApiFeatureFlagsSseRoute: typeof ApiFeatureFlagsSseRoute
  ApiJobsEnqueueRoute: typeof ApiJobsEnqueueRoute
  ApiJobsManageRoute: typeof ApiJobsManageRoute
  ApiJobsProcessRoute: typeof ApiJobsProcessRoute
  ApiJobsStatusRoute: typeof ApiJobsStatusRoute
  ApiKycAdminRoute: typeof ApiKycAdminRoute
  ApiKycDocumentsRoute: typeof ApiKycDocumentsRoute
  ApiKycSubmitRoute: typeof ApiKycSubmitRoute
  ApiKycTiersRoute: typeof ApiKycTiersRoute
  ApiMonitoringAlertsRoute: typeof ApiMonitoringAlertsRoute
  ApiMonitoringHealthCheckRoute: typeof ApiMonitoringHealthCheckRoute
  ApiMonitoringStatusRoute: typeof ApiMonitoringStatusRoute
  ApiOnboardingLinkAccountRoute: typeof ApiOnboardingLinkAccountRoute
  ApiOnboardingResendOtpRoute: typeof ApiOnboardingResendOtpRoute
  ApiOnboardingSessionRoute: typeof ApiOnboardingSessionRoute
  ApiOnboardingStartRoute: typeof ApiOnboardingStartRoute
  ApiOnboardingVerifyOtpRoute: typeof ApiOnboardingVerifyOtpRoute
  ApiOverdueTasksMonitorRoute: typeof ApiOverdueTasksMonitorRoute
  ApiPushAndroidConfigRoute: typeof ApiPushAndroidConfigRoute
  ApiPushAndroidInteractionRoute: typeof ApiPushAndroidInteractionRoute
  ApiPushDeepLinkRoute: typeof ApiPushDeepLinkRoute
  ApiPushProcessQueueRoute: typeof ApiPushProcessQueueRoute
  ApiRecordingRetentionRoute: typeof ApiRecordingRetentionRoute
  ApiRecordingWebhookRoute: typeof ApiRecordingWebhookRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTasksRemindersRoute: typeof ApiTasksRemindersRoute
  ApiTeamCapacityMonitorRoute: typeof ApiTeamCapacityMonitorRoute
  ApiVoucherAlertsMonitorRoute: typeof ApiVoucherAlertsMonitorRoute
  ApiWorkflowsEventRoute: typeof ApiWorkflowsEventRoute
  ApiWorkflowsProcessRoute: typeof ApiWorkflowsProcessRoute
  ApiWorkflowsWebhookRoute: typeof ApiWorkflowsWebhookRoute
  MobileCallPhoneOrUserIdRoute: typeof MobileCallPhoneOrUserIdRoute
  MobileExpensesIdRoute: typeof MobileExpensesIdRoute
  MobileExpensesNewRoute: typeof MobileExpensesNewRoute
  MobileFieldTechHistoryRoute: typeof MobileFieldTechHistoryRoute
  MobileFieldTechInventoryRoute: typeof MobileFieldTechInventoryRoute
  MobileFieldTechRoutePlanRoute: typeof MobileFieldTechRoutePlanRoute
  MobileFieldTechWorkOrdersRoute: typeof MobileFieldTechWorkOrdersRoute
  MobileKycSubmitRoute: typeof MobileKycSubmitRoute
  MobilePayCodeRoute: typeof MobilePayCodeRoute
  MobilePostCallCallIdRoute: typeof MobilePostCallCallIdRoute
  MobileTopupTransactionIdRoute: typeof MobileTopupTransactionIdRoute
  MobileTopupHistoryRoute: typeof MobileTopupHistoryRoute
  MobileVouchersIdRoute: typeof MobileVouchersIdRoute
  ApiDataExportIndexRoute: typeof ApiDataExportIndexRoute
  ApiKycIndexRoute: typeof ApiKycIndexRoute
  MobileApprovalsIndexRoute: typeof MobileApprovalsIndexRoute
  MobileBriefingIndexRoute: typeof MobileBriefingIndexRoute
  MobileCallIndexRoute: typeof MobileCallIndexRoute
  MobileExpensesIndexRoute: typeof MobileExpensesIndexRoute
  MobileFieldTechIndexRoute: typeof MobileFieldTechIndexRoute
  MobileKycIndexRoute: typeof MobileKycIndexRoute
  MobilePayIndexRoute: typeof MobilePayIndexRoute
  MobileTopupIndexRoute: typeof MobileTopupIndexRoute
  MobileVouchersIndexRoute: typeof MobileVouchersIndexRoute
  ProfileUserIdIndexRoute: typeof ProfileUserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/voice-input': {
      id: '/demo/voice-input'
      path: '/demo/voice-input'
      fullPath: '/demo/voice-input'
      preLoaderRoute: typeof DemoVoiceInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/receipt-capture': {
      id: '/demo/receipt-capture'
      path: '/demo/receipt-capture'
      fullPath: '/demo/receipt-capture'
      preLoaderRoute: typeof DemoReceiptCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ocr-receipt': {
      id: '/demo/ocr-receipt'
      path: '/demo/ocr-receipt'
      fullPath: '/demo/ocr-receipt'
      preLoaderRoute: typeof DemoOcrReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/demo/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/task-threads': {
      id: '/dashboard/task-threads'
      path: '/task-threads'
      fullPath: '/dashboard/task-threads'
      preLoaderRoute: typeof DashboardTaskThreadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/task-rules': {
      id: '/dashboard/task-rules'
      path: '/task-rules'
      fullPath: '/dashboard/task-rules'
      preLoaderRoute: typeof DashboardTaskRulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/search': {
      id: '/dashboard/search'
      path: '/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/query': {
      id: '/dashboard/query'
      path: '/query'
      fullPath: '/dashboard/query'
      preLoaderRoute: typeof DashboardQueryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/profile/$userId/': {
      id: '/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/vouchers/': {
      id: '/mobile/vouchers/'
      path: '/mobile/vouchers'
      fullPath: '/mobile/vouchers'
      preLoaderRoute: typeof MobileVouchersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/topup/': {
      id: '/mobile/topup/'
      path: '/mobile/topup'
      fullPath: '/mobile/topup'
      preLoaderRoute: typeof MobileTopupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/pay/': {
      id: '/mobile/pay/'
      path: '/mobile/pay'
      fullPath: '/mobile/pay'
      preLoaderRoute: typeof MobilePayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/kyc/': {
      id: '/mobile/kyc/'
      path: '/mobile/kyc'
      fullPath: '/mobile/kyc'
      preLoaderRoute: typeof MobileKycIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/field-tech/': {
      id: '/mobile/field-tech/'
      path: '/mobile/field-tech'
      fullPath: '/mobile/field-tech'
      preLoaderRoute: typeof MobileFieldTechIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/expenses/': {
      id: '/mobile/expenses/'
      path: '/mobile/expenses'
      fullPath: '/mobile/expenses'
      preLoaderRoute: typeof MobileExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/call/': {
      id: '/mobile/call/'
      path: '/mobile/call'
      fullPath: '/mobile/call'
      preLoaderRoute: typeof MobileCallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/briefing/': {
      id: '/mobile/briefing/'
      path: '/mobile/briefing'
      fullPath: '/mobile/briefing'
      preLoaderRoute: typeof MobileBriefingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/approvals/': {
      id: '/mobile/approvals/'
      path: '/mobile/approvals'
      fullPath: '/mobile/approvals'
      preLoaderRoute: typeof MobileApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet/': {
      id: '/dashboard/wallet/'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vouchers/': {
      id: '/dashboard/vouchers/'
      path: '/vouchers'
      fullPath: '/dashboard/vouchers'
      preLoaderRoute: typeof DashboardVouchersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sales/': {
      id: '/dashboard/sales/'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof DashboardSalesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reconciliation/': {
      id: '/dashboard/reconciliation/'
      path: '/reconciliation'
      fullPath: '/dashboard/reconciliation'
      preLoaderRoute: typeof DashboardReconciliationIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/md/': {
      id: '/dashboard/md/'
      path: '/md'
      fullPath: '/dashboard/md'
      preLoaderRoute: typeof DashboardMdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kyc/': {
      id: '/dashboard/kyc/'
      path: '/kyc'
      fullPath: '/dashboard/kyc'
      preLoaderRoute: typeof DashboardKycIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customer-issues/': {
      id: '/dashboard/customer-issues/'
      path: '/customer-issues'
      fullPath: '/dashboard/customer-issues'
      preLoaderRoute: typeof DashboardCustomerIssuesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approvals/': {
      id: '/dashboard/approvals/'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/kyc/': {
      id: '/api/kyc/'
      path: '/api/kyc'
      fullPath: '/api/kyc'
      preLoaderRoute: typeof ApiKycIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data-export/': {
      id: '/api/data-export/'
      path: '/api/data-export'
      fullPath: '/api/data-export'
      preLoaderRoute: typeof ApiDataExportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/vouchers/$id': {
      id: '/mobile/vouchers/$id'
      path: '/mobile/vouchers/$id'
      fullPath: '/mobile/vouchers/$id'
      preLoaderRoute: typeof MobileVouchersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/topup/history': {
      id: '/mobile/topup/history'
      path: '/mobile/topup/history'
      fullPath: '/mobile/topup/history'
      preLoaderRoute: typeof MobileTopupHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/topup/$transactionId': {
      id: '/mobile/topup/$transactionId'
      path: '/mobile/topup/$transactionId'
      fullPath: '/mobile/topup/$transactionId'
      preLoaderRoute: typeof MobileTopupTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/post-call/$callId': {
      id: '/mobile/post-call/$callId'
      path: '/mobile/post-call/$callId'
      fullPath: '/mobile/post-call/$callId'
      preLoaderRoute: typeof MobilePostCallCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/pay/$code': {
      id: '/mobile/pay/$code'
      path: '/mobile/pay/$code'
      fullPath: '/mobile/pay/$code'
      preLoaderRoute: typeof MobilePayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/kyc/submit': {
      id: '/mobile/kyc/submit'
      path: '/mobile/kyc/submit'
      fullPath: '/mobile/kyc/submit'
      preLoaderRoute: typeof MobileKycSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/field-tech/work-orders': {
      id: '/mobile/field-tech/work-orders'
      path: '/mobile/field-tech/work-orders'
      fullPath: '/mobile/field-tech/work-orders'
      preLoaderRoute: typeof MobileFieldTechWorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/field-tech/route-plan': {
      id: '/mobile/field-tech/route-plan'
      path: '/mobile/field-tech/route-plan'
      fullPath: '/mobile/field-tech/route-plan'
      preLoaderRoute: typeof MobileFieldTechRoutePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/field-tech/inventory': {
      id: '/mobile/field-tech/inventory'
      path: '/mobile/field-tech/inventory'
      fullPath: '/mobile/field-tech/inventory'
      preLoaderRoute: typeof MobileFieldTechInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/field-tech/history': {
      id: '/mobile/field-tech/history'
      path: '/mobile/field-tech/history'
      fullPath: '/mobile/field-tech/history'
      preLoaderRoute: typeof MobileFieldTechHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/expenses/new': {
      id: '/mobile/expenses/new'
      path: '/mobile/expenses/new'
      fullPath: '/mobile/expenses/new'
      preLoaderRoute: typeof MobileExpensesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/expenses/$id': {
      id: '/mobile/expenses/$id'
      path: '/mobile/expenses/$id'
      fullPath: '/mobile/expenses/$id'
      preLoaderRoute: typeof MobileExpensesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/call/$phoneOrUserId': {
      id: '/mobile/call/$phoneOrUserId'
      path: '/mobile/call/$phoneOrUserId'
      fullPath: '/mobile/call/$phoneOrUserId'
      preLoaderRoute: typeof MobileCallPhoneOrUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet/transactions': {
      id: '/dashboard/wallet/transactions'
      path: '/wallet/transactions'
      fullPath: '/dashboard/wallet/transactions'
      preLoaderRoute: typeof DashboardWalletTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vouchers/create': {
      id: '/dashboard/vouchers/create'
      path: '/vouchers/create'
      fullPath: '/dashboard/vouchers/create'
      preLoaderRoute: typeof DashboardVouchersCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vouchers/$id': {
      id: '/dashboard/vouchers/$id'
      path: '/vouchers/$id'
      fullPath: '/dashboard/vouchers/$id'
      preLoaderRoute: typeof DashboardVouchersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/workflows/webhook': {
      id: '/api/workflows/webhook'
      path: '/api/workflows/webhook'
      fullPath: '/api/workflows/webhook'
      preLoaderRoute: typeof ApiWorkflowsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/process': {
      id: '/api/workflows/process'
      path: '/api/workflows/process'
      fullPath: '/api/workflows/process'
      preLoaderRoute: typeof ApiWorkflowsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/event': {
      id: '/api/workflows/event'
      path: '/api/workflows/event'
      fullPath: '/api/workflows/event'
      preLoaderRoute: typeof ApiWorkflowsEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voucher-alerts/monitor': {
      id: '/api/voucher-alerts/monitor'
      path: '/api/voucher-alerts/monitor'
      fullPath: '/api/voucher-alerts/monitor'
      preLoaderRoute: typeof ApiVoucherAlertsMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team-capacity/monitor': {
      id: '/api/team-capacity/monitor'
      path: '/api/team-capacity/monitor'
      fullPath: '/api/team-capacity/monitor'
      preLoaderRoute: typeof ApiTeamCapacityMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/reminders': {
      id: '/api/tasks/reminders'
      path: '/api/tasks/reminders'
      fullPath: '/api/tasks/reminders'
      preLoaderRoute: typeof ApiTasksRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recording/webhook': {
      id: '/api/recording/webhook'
      path: '/api/recording/webhook'
      fullPath: '/api/recording/webhook'
      preLoaderRoute: typeof ApiRecordingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recording/retention': {
      id: '/api/recording/retention'
      path: '/api/recording/retention'
      fullPath: '/api/recording/retention'
      preLoaderRoute: typeof ApiRecordingRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/process-queue': {
      id: '/api/push/process-queue'
      path: '/api/push/process-queue'
      fullPath: '/api/push/process-queue'
      preLoaderRoute: typeof ApiPushProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/deep-link': {
      id: '/api/push/deep-link'
      path: '/api/push/deep-link'
      fullPath: '/api/push/deep-link'
      preLoaderRoute: typeof ApiPushDeepLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/android-interaction': {
      id: '/api/push/android-interaction'
      path: '/api/push/android-interaction'
      fullPath: '/api/push/android-interaction'
      preLoaderRoute: typeof ApiPushAndroidInteractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/android-config': {
      id: '/api/push/android-config'
      path: '/api/push/android-config'
      fullPath: '/api/push/android-config'
      preLoaderRoute: typeof ApiPushAndroidConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overdue-tasks/monitor': {
      id: '/api/overdue-tasks/monitor'
      path: '/api/overdue-tasks/monitor'
      fullPath: '/api/overdue-tasks/monitor'
      preLoaderRoute: typeof ApiOverdueTasksMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/verify-otp': {
      id: '/api/onboarding/verify-otp'
      path: '/api/onboarding/verify-otp'
      fullPath: '/api/onboarding/verify-otp'
      preLoaderRoute: typeof ApiOnboardingVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/start': {
      id: '/api/onboarding/start'
      path: '/api/onboarding/start'
      fullPath: '/api/onboarding/start'
      preLoaderRoute: typeof ApiOnboardingStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/session': {
      id: '/api/onboarding/session'
      path: '/api/onboarding/session'
      fullPath: '/api/onboarding/session'
      preLoaderRoute: typeof ApiOnboardingSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/resend-otp': {
      id: '/api/onboarding/resend-otp'
      path: '/api/onboarding/resend-otp'
      fullPath: '/api/onboarding/resend-otp'
      preLoaderRoute: typeof ApiOnboardingResendOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/link-account': {
      id: '/api/onboarding/link-account'
      path: '/api/onboarding/link-account'
      fullPath: '/api/onboarding/link-account'
      preLoaderRoute: typeof ApiOnboardingLinkAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitoring/status': {
      id: '/api/monitoring/status'
      path: '/api/monitoring/status'
      fullPath: '/api/monitoring/status'
      preLoaderRoute: typeof ApiMonitoringStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitoring/health-check': {
      id: '/api/monitoring/health-check'
      path: '/api/monitoring/health-check'
      fullPath: '/api/monitoring/health-check'
      preLoaderRoute: typeof ApiMonitoringHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monitoring/alerts': {
      id: '/api/monitoring/alerts'
      path: '/api/monitoring/alerts'
      fullPath: '/api/monitoring/alerts'
      preLoaderRoute: typeof ApiMonitoringAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kyc/tiers': {
      id: '/api/kyc/tiers'
      path: '/api/kyc/tiers'
      fullPath: '/api/kyc/tiers'
      preLoaderRoute: typeof ApiKycTiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kyc/submit': {
      id: '/api/kyc/submit'
      path: '/api/kyc/submit'
      fullPath: '/api/kyc/submit'
      preLoaderRoute: typeof ApiKycSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kyc/documents': {
      id: '/api/kyc/documents'
      path: '/api/kyc/documents'
      fullPath: '/api/kyc/documents'
      preLoaderRoute: typeof ApiKycDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kyc/admin': {
      id: '/api/kyc/admin'
      path: '/api/kyc/admin'
      fullPath: '/api/kyc/admin'
      preLoaderRoute: typeof ApiKycAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/status': {
      id: '/api/jobs/status'
      path: '/api/jobs/status'
      fullPath: '/api/jobs/status'
      preLoaderRoute: typeof ApiJobsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/process': {
      id: '/api/jobs/process'
      path: '/api/jobs/process'
      fullPath: '/api/jobs/process'
      preLoaderRoute: typeof ApiJobsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/manage': {
      id: '/api/jobs/manage'
      path: '/api/jobs/manage'
      fullPath: '/api/jobs/manage'
      preLoaderRoute: typeof ApiJobsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/enqueue': {
      id: '/api/jobs/enqueue'
      path: '/api/jobs/enqueue'
      fullPath: '/api/jobs/enqueue'
      preLoaderRoute: typeof ApiJobsEnqueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feature-flags/sse': {
      id: '/api/feature-flags/sse'
      path: '/api/feature-flags/sse'
      fullPath: '/api/feature-flags/sse'
      preLoaderRoute: typeof ApiFeatureFlagsSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feature-flags/health': {
      id: '/api/feature-flags/health'
      path: '/api/feature-flags/health'
      fullPath: '/api/feature-flags/health'
      preLoaderRoute: typeof ApiFeatureFlagsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expense-compliance/monitor': {
      id: '/api/expense-compliance/monitor'
      path: '/api/expense-compliance/monitor'
      fullPath: '/api/expense-compliance/monitor'
      preLoaderRoute: typeof ApiExpenseComplianceMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-issues/stats': {
      id: '/api/customer-issues/stats'
      path: '/api/customer-issues/stats'
      fullPath: '/api/customer-issues/stats'
      preLoaderRoute: typeof ApiCustomerIssuesStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-issues/sla': {
      id: '/api/customer-issues/sla'
      path: '/api/customer-issues/sla'
      fullPath: '/api/customer-issues/sla'
      preLoaderRoute: typeof ApiCustomerIssuesSlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-issues/risks': {
      id: '/api/customer-issues/risks'
      path: '/api/customer-issues/risks'
      fullPath: '/api/customer-issues/risks'
      preLoaderRoute: typeof ApiCustomerIssuesRisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-issues/monitor': {
      id: '/api/customer-issues/monitor'
      path: '/api/customer-issues/monitor'
      fullPath: '/api/customer-issues/monitor'
      preLoaderRoute: typeof ApiCustomerIssuesMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/briefing/schedule': {
      id: '/api/briefing/schedule'
      path: '/api/briefing/schedule'
      fullPath: '/api/briefing/schedule'
      preLoaderRoute: typeof ApiBriefingScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anomaly-detection/analyze': {
      id: '/api/anomaly-detection/analyze'
      path: '/api/anomaly-detection/analyze'
      fullPath: '/api/anomaly-detection/analyze'
      preLoaderRoute: typeof ApiAnomalyDetectionAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anomaly-detection/alerts': {
      id: '/api/anomaly-detection/alerts'
      path: '/api/anomaly-detection/alerts'
      fullPath: '/api/anomaly-detection/alerts'
      preLoaderRoute: typeof ApiAnomalyDetectionAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardQueryRoute: typeof DashboardQueryRoute
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTaskRulesRoute: typeof DashboardTaskRulesRoute
  DashboardTaskThreadsRoute: typeof DashboardTaskThreadsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardVouchersIdRoute: typeof DashboardVouchersIdRoute
  DashboardVouchersCreateRoute: typeof DashboardVouchersCreateRoute
  DashboardWalletTransactionsRoute: typeof DashboardWalletTransactionsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardApprovalsIndexRoute: typeof DashboardApprovalsIndexRoute
  DashboardCustomerIssuesIndexRoute: typeof DashboardCustomerIssuesIndexRoute
  DashboardKycIndexRoute: typeof DashboardKycIndexRoute
  DashboardMdIndexRoute: typeof DashboardMdIndexRoute
  DashboardReconciliationIndexRoute: typeof DashboardReconciliationIndexRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardSalesIndexRoute: typeof DashboardSalesIndexRoute
  DashboardVouchersIndexRoute: typeof DashboardVouchersIndexRoute
  DashboardWalletIndexRoute: typeof DashboardWalletIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardQueryRoute: DashboardQueryRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTaskRulesRoute: DashboardTaskRulesRoute,
  DashboardTaskThreadsRoute: DashboardTaskThreadsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardVouchersIdRoute: DashboardVouchersIdRoute,
  DashboardVouchersCreateRoute: DashboardVouchersCreateRoute,
  DashboardWalletTransactionsRoute: DashboardWalletTransactionsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardApprovalsIndexRoute: DashboardApprovalsIndexRoute,
  DashboardCustomerIssuesIndexRoute: DashboardCustomerIssuesIndexRoute,
  DashboardKycIndexRoute: DashboardKycIndexRoute,
  DashboardMdIndexRoute: DashboardMdIndexRoute,
  DashboardReconciliationIndexRoute: DashboardReconciliationIndexRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardSalesIndexRoute: DashboardSalesIndexRoute,
  DashboardVouchersIndexRoute: DashboardVouchersIndexRoute,
  DashboardWalletIndexRoute: DashboardWalletIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoOcrReceiptRoute: DemoOcrReceiptRoute,
  DemoReceiptCaptureRoute: DemoReceiptCaptureRoute,
  DemoVoiceInputRoute: DemoVoiceInputRoute,
  DemoIndexRoute: DemoIndexRoute,
  MobileIndexRoute: MobileIndexRoute,
  ApiAnomalyDetectionAlertsRoute: ApiAnomalyDetectionAlertsRoute,
  ApiAnomalyDetectionAnalyzeRoute: ApiAnomalyDetectionAnalyzeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBriefingScheduleRoute: ApiBriefingScheduleRoute,
  ApiCustomerIssuesMonitorRoute: ApiCustomerIssuesMonitorRoute,
  ApiCustomerIssuesRisksRoute: ApiCustomerIssuesRisksRoute,
  ApiCustomerIssuesSlaRoute: ApiCustomerIssuesSlaRoute,
  ApiCustomerIssuesStatsRoute: ApiCustomerIssuesStatsRoute,
  ApiExpenseComplianceMonitorRoute: ApiExpenseComplianceMonitorRoute,
  ApiFeatureFlagsHealthRoute: ApiFeatureFlagsHealthRoute,
  ApiFeatureFlagsSseRoute: ApiFeatureFlagsSseRoute,
  ApiJobsEnqueueRoute: ApiJobsEnqueueRoute,
  ApiJobsManageRoute: ApiJobsManageRoute,
  ApiJobsProcessRoute: ApiJobsProcessRoute,
  ApiJobsStatusRoute: ApiJobsStatusRoute,
  ApiKycAdminRoute: ApiKycAdminRoute,
  ApiKycDocumentsRoute: ApiKycDocumentsRoute,
  ApiKycSubmitRoute: ApiKycSubmitRoute,
  ApiKycTiersRoute: ApiKycTiersRoute,
  ApiMonitoringAlertsRoute: ApiMonitoringAlertsRoute,
  ApiMonitoringHealthCheckRoute: ApiMonitoringHealthCheckRoute,
  ApiMonitoringStatusRoute: ApiMonitoringStatusRoute,
  ApiOnboardingLinkAccountRoute: ApiOnboardingLinkAccountRoute,
  ApiOnboardingResendOtpRoute: ApiOnboardingResendOtpRoute,
  ApiOnboardingSessionRoute: ApiOnboardingSessionRoute,
  ApiOnboardingStartRoute: ApiOnboardingStartRoute,
  ApiOnboardingVerifyOtpRoute: ApiOnboardingVerifyOtpRoute,
  ApiOverdueTasksMonitorRoute: ApiOverdueTasksMonitorRoute,
  ApiPushAndroidConfigRoute: ApiPushAndroidConfigRoute,
  ApiPushAndroidInteractionRoute: ApiPushAndroidInteractionRoute,
  ApiPushDeepLinkRoute: ApiPushDeepLinkRoute,
  ApiPushProcessQueueRoute: ApiPushProcessQueueRoute,
  ApiRecordingRetentionRoute: ApiRecordingRetentionRoute,
  ApiRecordingWebhookRoute: ApiRecordingWebhookRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTasksRemindersRoute: ApiTasksRemindersRoute,
  ApiTeamCapacityMonitorRoute: ApiTeamCapacityMonitorRoute,
  ApiVoucherAlertsMonitorRoute: ApiVoucherAlertsMonitorRoute,
  ApiWorkflowsEventRoute: ApiWorkflowsEventRoute,
  ApiWorkflowsProcessRoute: ApiWorkflowsProcessRoute,
  ApiWorkflowsWebhookRoute: ApiWorkflowsWebhookRoute,
  MobileCallPhoneOrUserIdRoute: MobileCallPhoneOrUserIdRoute,
  MobileExpensesIdRoute: MobileExpensesIdRoute,
  MobileExpensesNewRoute: MobileExpensesNewRoute,
  MobileFieldTechHistoryRoute: MobileFieldTechHistoryRoute,
  MobileFieldTechInventoryRoute: MobileFieldTechInventoryRoute,
  MobileFieldTechRoutePlanRoute: MobileFieldTechRoutePlanRoute,
  MobileFieldTechWorkOrdersRoute: MobileFieldTechWorkOrdersRoute,
  MobileKycSubmitRoute: MobileKycSubmitRoute,
  MobilePayCodeRoute: MobilePayCodeRoute,
  MobilePostCallCallIdRoute: MobilePostCallCallIdRoute,
  MobileTopupTransactionIdRoute: MobileTopupTransactionIdRoute,
  MobileTopupHistoryRoute: MobileTopupHistoryRoute,
  MobileVouchersIdRoute: MobileVouchersIdRoute,
  ApiDataExportIndexRoute: ApiDataExportIndexRoute,
  ApiKycIndexRoute: ApiKycIndexRoute,
  MobileApprovalsIndexRoute: MobileApprovalsIndexRoute,
  MobileBriefingIndexRoute: MobileBriefingIndexRoute,
  MobileCallIndexRoute: MobileCallIndexRoute,
  MobileExpensesIndexRoute: MobileExpensesIndexRoute,
  MobileFieldTechIndexRoute: MobileFieldTechIndexRoute,
  MobileKycIndexRoute: MobileKycIndexRoute,
  MobilePayIndexRoute: MobilePayIndexRoute,
  MobileTopupIndexRoute: MobileTopupIndexRoute,
  MobileVouchersIndexRoute: MobileVouchersIndexRoute,
  ProfileUserIdIndexRoute: ProfileUserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
